name: linphone
description: A new Flutter project.

version: 1.0.0+1
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter

  flutter_pjsip:
    path: ./flutter_pjsip
  
  shared_preferences: ^2.5.2
  # flutter_openvpn: 
  #   path: ./flutter_openvpn
  permission_handler: ^11.1.0
  provider: 6.1.2
  logger: ^2.5.0
  flutter_svg: ^2.0.17
  ftpconnect: ^2.0.7
  badges: ^3.1.2
  grouped_list: ^6.0.0
  intl: ^0.19.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  http: ^1.3.0
  path: ^1.9.1
  flutter_contacts: ^1.1.9+2
  image: ^4.5.3
  loader_overlay: ^5.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.5
  audioplayers: ^6.4.0
  flutter_xlider: ^3.5.0
  flutter_local_notifications: ^19.1.0
  vibration:  ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/user.svg
   - assets/images/user_fill.svg
   - assets/images/Bellsvg.svg
   - assets/images/search.svg
   - assets/images/settings_fill.svg
   - assets/images/settings_outline.svg
   - assets/images/bubble_outline.svg
   - assets/images/bubble_fill.svg
   - assets/images/mic.svg
   - assets/images/incoming.svg
   - assets/images/outgoing.svg
   - assets/images/keypad.svg
   - assets/images/call_fill.svg
   - assets/images/call_outline.svg
   - assets/images/del.svg
   - assets/images/contact_fill.svg
   - assets/images/contact_outline.svg
   - assets/images/pin.svg
   - assets/images/unpin.svg
   - assets/images/add_circle.svg
   - assets/images/arrow_left.svg
   - assets/images/attachment.svg
   - assets/images/camera.svg
   - assets/images/image.svg
   - assets/images/sent.svg
   - assets/images/topRight.svg
   - assets/images/bottomLeft.svg
   - assets/images/logo.png
   - assets/vpn/OpenVPN.ovpn
   - assets/images/mute.svg
   - assets/images/speaker.svg
   - assets/images/bluetooth.svg
   - assets/images/call_hold.svg
   - assets/images/call_add.svg
   - assets/images/user_no_outline.svg
   - assets/images/info.svg
   - assets/images/trash.svg
   - assets/images/play.svg
   - assets/images/pause.svg
   - assets/images/animated-bell.gif