name: dart_sip_ua_example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  sip_ua:
    path: ../
  shared_preferences: ^2.5.2
  permission_handler: ^11.1.0
  flutter_webrtc: ^0.12.6
  provider: 6.1.2
  logger: ^2.5.0
  flutter_svg: ^2.0.17
  badges: ^3.1.2
  grouped_list: ^6.0.0
  intl: ^0.20.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/user.svg
   - assets/images/Bellsvg.svg
   - assets/images/search.svg
   - assets/images/settings_fill.svg
   - assets/images/settings_outline.svg
   - assets/images/bubble_outline.svg
   - assets/images/bubble_fill.svg
   - assets/images/mic.svg
   - assets/images/incoming.svg
   - assets/images/outgoing.svg
   - assets/images/keypad.svg
   - assets/images/call_fill.svg
   - assets/images/call_outline.svg
   - assets/images/del.svg
   - assets/images/contact_fill.svg
   - assets/images/contact_outline.svg
   - assets/images/pin.svg
   - assets/images/add_circle.svg
   - assets/images/arrow_left.svg
   - assets/images/attachment.svg
   - assets/images/camera.svg
   - assets/images/image.svg
   - assets/images/sent.svg
