// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLuFSq6fpzxSyG7aQ5xCzoq3yc3TzckF0',
    appId: '1:1086415542778:web:50791c97832d451b10ac43',
    messagingSenderId: '1086415542778',
    projectId: 'linphone-ea724',
    authDomain: 'linphone-ea724.firebaseapp.com',
    storageBucket: 'linphone-ea724.firebasestorage.app',
    measurementId: 'G-354X4XJ21G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtZAVMkwrLmv58ZX31UyzzraI1kZf_0Q',
    appId: '1:1086415542778:android:004535a42717358c10ac43',
    messagingSenderId: '1086415542778',
    projectId: 'linphone-ea724',
    storageBucket: 'linphone-ea724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0CPlVuDDufrS7zd5wwVe7LS9uzvaecE',
    appId: '1:1086415542778:ios:4f4d4fffcfb163e910ac43',
    messagingSenderId: '1086415542778',
    projectId: 'linphone-ea724',
    storageBucket: 'linphone-ea724.firebasestorage.app',
    iosBundleId: 'com.github.cloudwebrtc.dartSipUaExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0CPlVuDDufrS7zd5wwVe7LS9uzvaecE',
    appId: '1:1086415542778:ios:4f4d4fffcfb163e910ac43',
    messagingSenderId: '1086415542778',
    projectId: 'linphone-ea724',
    storageBucket: 'linphone-ea724.firebasestorage.app',
    iosBundleId: 'com.github.cloudwebrtc.dartSipUaExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLuFSq6fpzxSyG7aQ5xCzoq3yc3TzckF0',
    appId: '1:1086415542778:web:242418f553af62ea10ac43',
    messagingSenderId: '1086415542778',
    projectId: 'linphone-ea724',
    authDomain: 'linphone-ea724.firebaseapp.com',
    storageBucket: 'linphone-ea724.firebasestorage.app',
    measurementId: 'G-SSR199ZEZC',
  );
}
